name: CI-CD DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: [self-hosted, Windows, X64, dev]

    steps:
      - uses: actions/checkout@v4

      - name: Load kubeconfig
        shell: powershell
        run: |
          "${{ secrets.KUBECONFIG_DEV }}" | Out-File kubeconfig.yaml -Encoding ascii
          $env:KUBECONFIG="$PWD\kubeconfig.yaml"

      - name: Deploy DEV
        shell: powershell
        run: kubectl apply -f dev/ --validate=false
