name: CI-CD PROD

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: [self-hosted, Windows, X64, prod]

    steps:
      - uses: actions/checkout@v4

      - name: Load kubeconfig
        shell: powershell
        run: |
          "${{ secrets.KUBECONFIG_PROD }}" | Out-File kubeconfig.yaml -Encoding ascii
          $env:KUBECONFIG="$PWD\kubeconfig.yaml"

      - name: Deploy PROD
        shell: powershell
        run: kubectl apply -f prod/ --validate=false
