name: CD - Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git SHA
        shell: powershell
        run: |
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV

      - name: Show SHA
        shell: powershell
        run: |
          echo "Deploying SHA=$env:GIT_SHA"

      - name: Deploy backend to DEV
        shell: powershell
        run: |
          kubectl set image deployment/backend backend=backend-app:$env:GIT_SHA -n app-dev

      - name: Deploy frontend to DEV
        shell: powershell
        run: |
          kubectl set image deployment/frontend frontend=frontend-app:$env:GIT_SHA -n app-dev
